// Inputs
export const SELECT_UNIT = 'SELECT_UNIT';
export const SET_ALTITUDE = 'SET_ALTITUDE';
export const SET_OVEN_TEMP = 'SET_OVEN_TEMP';
export const SET_BAKING_TIME = 'SET_BAKING_TIME';
export const SET_LIQUIDS = 'SET_LIQUIDS';
export const SET_FLOUR = 'SET_FLOUR';
export const SET_FLOUR_CUPS = 'SET_FLOUR_CUPS';
export const SET_FLOUR_TBSP = 'SET_FLOUR_TBSP';
export const SET_SUGAR = 'SET_SUGAR';
export const SET_BAKING_MINS = 'SET_BAKING_MINS';
export const SET_BAKING_HOURS = 'SET_BAKING_HOURS';
export const SET_BAKING_POWDER = 'SET_BAKING_POWDER';
export const SET_YEAST = 'SET_YEAST';

// Outputs and calculations
export const CALCULATE_MIN_OVEN_TEMP = 'CALCULATE_MIN_OVEN_TEMP';
export const CALCULATE_MAX_OVEN_TEMP = 'CALCULATE_MAX_OVEN_TEMP';
export const CALCULATE_BAKING_POWDER = 'CALCULATE_BAKING_POWDER';
export const CALCULATE_MIN_TIME = 'CALCULATE_MIN_TIME';
export const CALCULATE_MAX_TIME = 'CALCULATE_MAX_TIME';
export const CALCULATE_YEAST = 'CALCULATE_YEAST';
export const CALCULATE_FLOUR = 'CALCULATE_FLOUR';
export const SET_DISPLAY_TEMP = 'SET_DISPLAY_TEMP';
export const SET_DISPLAY_TIME = 'SET_DISPLAY_TIME';
export const SET_DISPLAY_FLOUR = 'SET_DISPLAY_FLOUR';

// Form actions
export const CLEAR_FORM = 'CLEAR_FORM';
