/**
 * Customary
 */

// Inputs
export const SELECT_UNIT = 'SELECT_UNIT';
export const SET_ALTITUDE = 'SET_ALTITUDE';

export const SET_OVEN_TEMP = 'SET_OVEN_TEMP';
export const SET_BAKING_TIME = 'SET_BAKING_TIME';
export const SET_BAKING_MINS = 'SET_BAKING_MINS';
export const SET_BAKING_HOURS = 'SET_BAKING_HOURS';

export const SET_LIQUID_CUPS = 'SET_LIQUID_CUPS';
export const SET_LIQUID_PARTIAL_CUP = 'SET_LIQUID_PARTIAL_CUP';
export const SET_LIQUID_TBSP = 'SET_LIQUID_TBSP';
export const SET_LIQUID_TOTAL = 'SET_LIQUID_TOTAL';

export const SET_FLOUR = 'SET_FLOUR';
export const SET_FLOUR_CUPS = 'SET_FLOUR_CUPS';
export const SET_FLOUR_PARTIAL_CUP = 'SET_FLOUR_PARTIAL_CUP ';
export const SET_FLOUR_TBSP = 'SET_FLOUR_TBSP';
export const SET_FLOUR_TOTAL = 'SET_FLOUR_TOTAL';

export const SET_SUGAR_CUPS = 'SET_SUGAR_CUPS';
export const SET_SUGAR_PARTIAL_CUP = 'SET_SUGAR_PARTIAL_CUP';
export const SET_SUGAR_TBSP = 'SET_SUGAR_TBSP';
export const SET_SUGAR_TOTAL = 'SET_SUGAR_TOTAL';

export const SET_BAKING_POWDER = 'SET_BAKING_POWDER';
export const SET_BAKING_POWDER_TSP = 'SET_BAKING_POWDER_TSP';
export const SET_BAKING_POWDER_PARTIAL_TSP = 'SET_BAKING_POWDER_PARTIAL_TSP';
export const SET_BAKING_POWDER_TOTAL = 'SET_BAKING_POWDER_TOTAL';


export const SET_BAKING_SODA_TSP = 'SET_BAKING_SODA_TSP';
export const SET_BAKING_SODA_PARTIAL_TSP = 'SET_BAKING_SODA_PARTIAL_TSP';
export const SET_BAKING_SODA = 'SET_BAKING_SODA';
export const SET_BAKING_SODA_TOTAL = 'SET_BAKING_SODA_TOTAL';


export const SET_YEAST = 'SET_YEAST';
export const SET_YEAST_TSP = 'SET_YEAST_TSP';
export const SET_YEAST_PARTIAL_TSP = 'SET_YEAST_PARTIAL_TSP';
export const SET_YEAST_TOTAL = 'SET_YEAST_TOTAL';

// Outputs and calculations
export const CALCULATE_MIN_OVEN_TEMP = 'CALCULATE_MIN_OVEN_TEMP';
export const CALCULATE_MAX_OVEN_TEMP = 'CALCULATE_MAX_OVEN_TEMP';
export const CALCULATE_MIN_TIME = 'CALCULATE_MIN_TIME';
export const CALCULATE_MAX_TIME = 'CALCULATE_MAX_TIME';

export const CALCULATE_BAKING_POWDER = 'CALCULATE_BAKING_POWDER';
export const CALCULATE_YEAST = 'CALCULATE_YEAST';
export const CALCULATE_FLOUR = 'CALCULATE_FLOUR';
export const CALCULATE_MIN_LIQUID = 'CALCULATE_MIN_LIQUID';
export const CALCULATE_MAX_LIQUID = 'CALCULATE_MAX_LIQUID';
export const CALCULATE_SUGAR = 'CALCULATE_SUGAR';

// Setting custom strings to be displayed in fields
export const SET_DISPLAY_TEMP = 'SET_DISPLAY_TEMP';
export const SET_DISPLAY_TIME = 'SET_DISPLAY_TIME';
export const SET_DISPLAY_FLOUR = 'SET_DISPLAY_FLOUR';
export const SET_DISPLAY_LIQUID = 'SET_DISPLAY_LIQUID';
export const SET_DISPLAY_SUGAR = 'SET_DISPLAY_SUGAR';
export const SET_DISPLAY_YEAST = 'SET_DISPLAY_YEAST';
export const SET_DISPLAY_BAKING_POWDER = 'SET_DISPLAY_BAKING_POWDER';

// Form actions
export const CLEAR_FORM = 'CLEAR_FORM';


